package com.example.webdemo.dao;

import java.util.Date;

/**
 * 数据库表的映射，每个字段对应表中的一列
 */
public class Environment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Date
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Tempreature
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float tempreature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Humidity
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Light
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Integer light;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.PM25
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Integer pm25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.PM10
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Integer pm10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.PVtempreature
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float pvtempreature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Radiation
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Integer radiation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Vlot
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float vlot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current1
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current2
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current3
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current4
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current5
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current6
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current7
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current8
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current9
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current10
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current11
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current12
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current13
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current14
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current15
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column environment.Current16
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    private Float current16;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Date
     *
     * @return the value of environment.Date
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Date
     *
     * @param date the value for environment.Date
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Tempreature
     *
     * @return the value of environment.Tempreature
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getTempreature() {
        return tempreature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Tempreature
     *
     * @param tempreature the value for environment.Tempreature
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setTempreature(Float tempreature) {
        this.tempreature = tempreature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Humidity
     *
     * @return the value of environment.Humidity
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Humidity
     *
     * @param humidity the value for environment.Humidity
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setHumidity(Float humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Light
     *
     * @return the value of environment.Light
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Integer getLight() {
        return light;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Light
     *
     * @param light the value for environment.Light
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setLight(Integer light) {
        this.light = light;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.PM25
     *
     * @return the value of environment.PM25
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Integer getPm25() {
        return pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.PM25
     *
     * @param pm25 the value for environment.PM25
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setPm25(Integer pm25) {
        this.pm25 = pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.PM10
     *
     * @return the value of environment.PM10
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Integer getPm10() {
        return pm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.PM10
     *
     * @param pm10 the value for environment.PM10
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setPm10(Integer pm10) {
        this.pm10 = pm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.PVtempreature
     *
     * @return the value of environment.PVtempreature
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getPvtempreature() {
        return pvtempreature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.PVtempreature
     *
     * @param pvtempreature the value for environment.PVtempreature
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setPvtempreature(Float pvtempreature) {
        this.pvtempreature = pvtempreature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Radiation
     *
     * @return the value of environment.Radiation
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Integer getRadiation() {
        return radiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Radiation
     *
     * @param radiation the value for environment.Radiation
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setRadiation(Integer radiation) {
        this.radiation = radiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Vlot
     *
     * @return the value of environment.Vlot
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getVlot() {
        return vlot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Vlot
     *
     * @param vlot the value for environment.Vlot
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setVlot(Float vlot) {
        this.vlot = vlot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current1
     *
     * @return the value of environment.Current1
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent1() {
        return current1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current1
     *
     * @param current1 the value for environment.Current1
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent1(Float current1) {
        this.current1 = current1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current2
     *
     * @return the value of environment.Current2
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent2() {
        return current2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current2
     *
     * @param current2 the value for environment.Current2
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent2(Float current2) {
        this.current2 = current2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current3
     *
     * @return the value of environment.Current3
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent3() {
        return current3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current3
     *
     * @param current3 the value for environment.Current3
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent3(Float current3) {
        this.current3 = current3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current4
     *
     * @return the value of environment.Current4
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent4() {
        return current4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current4
     *
     * @param current4 the value for environment.Current4
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent4(Float current4) {
        this.current4 = current4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current5
     *
     * @return the value of environment.Current5
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent5() {
        return current5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current5
     *
     * @param current5 the value for environment.Current5
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent5(Float current5) {
        this.current5 = current5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current6
     *
     * @return the value of environment.Current6
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent6() {
        return current6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current6
     *
     * @param current6 the value for environment.Current6
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent6(Float current6) {
        this.current6 = current6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current7
     *
     * @return the value of environment.Current7
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent7() {
        return current7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current7
     *
     * @param current7 the value for environment.Current7
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent7(Float current7) {
        this.current7 = current7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current8
     *
     * @return the value of environment.Current8
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent8() {
        return current8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current8
     *
     * @param current8 the value for environment.Current8
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent8(Float current8) {
        this.current8 = current8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current9
     *
     * @return the value of environment.Current9
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent9() {
        return current9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current9
     *
     * @param current9 the value for environment.Current9
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent9(Float current9) {
        this.current9 = current9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current10
     *
     * @return the value of environment.Current10
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent10() {
        return current10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current10
     *
     * @param current10 the value for environment.Current10
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent10(Float current10) {
        this.current10 = current10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current11
     *
     * @return the value of environment.Current11
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent11() {
        return current11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current11
     *
     * @param current11 the value for environment.Current11
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent11(Float current11) {
        this.current11 = current11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current12
     *
     * @return the value of environment.Current12
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent12() {
        return current12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current12
     *
     * @param current12 the value for environment.Current12
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent12(Float current12) {
        this.current12 = current12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current13
     *
     * @return the value of environment.Current13
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent13() {
        return current13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current13
     *
     * @param current13 the value for environment.Current13
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent13(Float current13) {
        this.current13 = current13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current14
     *
     * @return the value of environment.Current14
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent14() {
        return current14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current14
     *
     * @param current14 the value for environment.Current14
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent14(Float current14) {
        this.current14 = current14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current15
     *
     * @return the value of environment.Current15
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent15() {
        return current15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current15
     *
     * @param current15 the value for environment.Current15
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent15(Float current15) {
        this.current15 = current15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column environment.Current16
     *
     * @return the value of environment.Current16
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Float getCurrent16() {
        return current16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column environment.Current16
     *
     * @param current16 the value for environment.Current16
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setCurrent16(Float current16) {
        this.current16 = current16;
    }
}