package com.example.webdemo.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnvironmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public EnvironmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDateIsNull() {
            addCriterion("Date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("Date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("Date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("Date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("Date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("Date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("Date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("Date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("Date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("Date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("Date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andTempreatureIsNull() {
            addCriterion("Tempreature is null");
            return (Criteria) this;
        }

        public Criteria andTempreatureIsNotNull() {
            addCriterion("Tempreature is not null");
            return (Criteria) this;
        }

        public Criteria andTempreatureEqualTo(Float value) {
            addCriterion("Tempreature =", value, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureNotEqualTo(Float value) {
            addCriterion("Tempreature <>", value, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureGreaterThan(Float value) {
            addCriterion("Tempreature >", value, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureGreaterThanOrEqualTo(Float value) {
            addCriterion("Tempreature >=", value, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureLessThan(Float value) {
            addCriterion("Tempreature <", value, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureLessThanOrEqualTo(Float value) {
            addCriterion("Tempreature <=", value, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureIn(List<Float> values) {
            addCriterion("Tempreature in", values, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureNotIn(List<Float> values) {
            addCriterion("Tempreature not in", values, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureBetween(Float value1, Float value2) {
            addCriterion("Tempreature between", value1, value2, "tempreature");
            return (Criteria) this;
        }

        public Criteria andTempreatureNotBetween(Float value1, Float value2) {
            addCriterion("Tempreature not between", value1, value2, "tempreature");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNull() {
            addCriterion("Humidity is null");
            return (Criteria) this;
        }

        public Criteria andHumidityIsNotNull() {
            addCriterion("Humidity is not null");
            return (Criteria) this;
        }

        public Criteria andHumidityEqualTo(Float value) {
            addCriterion("Humidity =", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotEqualTo(Float value) {
            addCriterion("Humidity <>", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThan(Float value) {
            addCriterion("Humidity >", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityGreaterThanOrEqualTo(Float value) {
            addCriterion("Humidity >=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThan(Float value) {
            addCriterion("Humidity <", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityLessThanOrEqualTo(Float value) {
            addCriterion("Humidity <=", value, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityIn(List<Float> values) {
            addCriterion("Humidity in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotIn(List<Float> values) {
            addCriterion("Humidity not in", values, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityBetween(Float value1, Float value2) {
            addCriterion("Humidity between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andHumidityNotBetween(Float value1, Float value2) {
            addCriterion("Humidity not between", value1, value2, "humidity");
            return (Criteria) this;
        }

        public Criteria andLightIsNull() {
            addCriterion("Light is null");
            return (Criteria) this;
        }

        public Criteria andLightIsNotNull() {
            addCriterion("Light is not null");
            return (Criteria) this;
        }

        public Criteria andLightEqualTo(Integer value) {
            addCriterion("Light =", value, "light");
            return (Criteria) this;
        }

        public Criteria andLightNotEqualTo(Integer value) {
            addCriterion("Light <>", value, "light");
            return (Criteria) this;
        }

        public Criteria andLightGreaterThan(Integer value) {
            addCriterion("Light >", value, "light");
            return (Criteria) this;
        }

        public Criteria andLightGreaterThanOrEqualTo(Integer value) {
            addCriterion("Light >=", value, "light");
            return (Criteria) this;
        }

        public Criteria andLightLessThan(Integer value) {
            addCriterion("Light <", value, "light");
            return (Criteria) this;
        }

        public Criteria andLightLessThanOrEqualTo(Integer value) {
            addCriterion("Light <=", value, "light");
            return (Criteria) this;
        }

        public Criteria andLightIn(List<Integer> values) {
            addCriterion("Light in", values, "light");
            return (Criteria) this;
        }

        public Criteria andLightNotIn(List<Integer> values) {
            addCriterion("Light not in", values, "light");
            return (Criteria) this;
        }

        public Criteria andLightBetween(Integer value1, Integer value2) {
            addCriterion("Light between", value1, value2, "light");
            return (Criteria) this;
        }

        public Criteria andLightNotBetween(Integer value1, Integer value2) {
            addCriterion("Light not between", value1, value2, "light");
            return (Criteria) this;
        }

        public Criteria andPm25IsNull() {
            addCriterion("PM25 is null");
            return (Criteria) this;
        }

        public Criteria andPm25IsNotNull() {
            addCriterion("PM25 is not null");
            return (Criteria) this;
        }

        public Criteria andPm25EqualTo(Integer value) {
            addCriterion("PM25 =", value, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25NotEqualTo(Integer value) {
            addCriterion("PM25 <>", value, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25GreaterThan(Integer value) {
            addCriterion("PM25 >", value, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25GreaterThanOrEqualTo(Integer value) {
            addCriterion("PM25 >=", value, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25LessThan(Integer value) {
            addCriterion("PM25 <", value, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25LessThanOrEqualTo(Integer value) {
            addCriterion("PM25 <=", value, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25In(List<Integer> values) {
            addCriterion("PM25 in", values, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25NotIn(List<Integer> values) {
            addCriterion("PM25 not in", values, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25Between(Integer value1, Integer value2) {
            addCriterion("PM25 between", value1, value2, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm25NotBetween(Integer value1, Integer value2) {
            addCriterion("PM25 not between", value1, value2, "pm25");
            return (Criteria) this;
        }

        public Criteria andPm10IsNull() {
            addCriterion("PM10 is null");
            return (Criteria) this;
        }

        public Criteria andPm10IsNotNull() {
            addCriterion("PM10 is not null");
            return (Criteria) this;
        }

        public Criteria andPm10EqualTo(Integer value) {
            addCriterion("PM10 =", value, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10NotEqualTo(Integer value) {
            addCriterion("PM10 <>", value, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10GreaterThan(Integer value) {
            addCriterion("PM10 >", value, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10GreaterThanOrEqualTo(Integer value) {
            addCriterion("PM10 >=", value, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10LessThan(Integer value) {
            addCriterion("PM10 <", value, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10LessThanOrEqualTo(Integer value) {
            addCriterion("PM10 <=", value, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10In(List<Integer> values) {
            addCriterion("PM10 in", values, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10NotIn(List<Integer> values) {
            addCriterion("PM10 not in", values, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10Between(Integer value1, Integer value2) {
            addCriterion("PM10 between", value1, value2, "pm10");
            return (Criteria) this;
        }

        public Criteria andPm10NotBetween(Integer value1, Integer value2) {
            addCriterion("PM10 not between", value1, value2, "pm10");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureIsNull() {
            addCriterion("PVtempreature is null");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureIsNotNull() {
            addCriterion("PVtempreature is not null");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureEqualTo(Float value) {
            addCriterion("PVtempreature =", value, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureNotEqualTo(Float value) {
            addCriterion("PVtempreature <>", value, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureGreaterThan(Float value) {
            addCriterion("PVtempreature >", value, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureGreaterThanOrEqualTo(Float value) {
            addCriterion("PVtempreature >=", value, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureLessThan(Float value) {
            addCriterion("PVtempreature <", value, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureLessThanOrEqualTo(Float value) {
            addCriterion("PVtempreature <=", value, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureIn(List<Float> values) {
            addCriterion("PVtempreature in", values, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureNotIn(List<Float> values) {
            addCriterion("PVtempreature not in", values, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureBetween(Float value1, Float value2) {
            addCriterion("PVtempreature between", value1, value2, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andPvtempreatureNotBetween(Float value1, Float value2) {
            addCriterion("PVtempreature not between", value1, value2, "pvtempreature");
            return (Criteria) this;
        }

        public Criteria andRadiationIsNull() {
            addCriterion("Radiation is null");
            return (Criteria) this;
        }

        public Criteria andRadiationIsNotNull() {
            addCriterion("Radiation is not null");
            return (Criteria) this;
        }

        public Criteria andRadiationEqualTo(Integer value) {
            addCriterion("Radiation =", value, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationNotEqualTo(Integer value) {
            addCriterion("Radiation <>", value, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationGreaterThan(Integer value) {
            addCriterion("Radiation >", value, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationGreaterThanOrEqualTo(Integer value) {
            addCriterion("Radiation >=", value, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationLessThan(Integer value) {
            addCriterion("Radiation <", value, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationLessThanOrEqualTo(Integer value) {
            addCriterion("Radiation <=", value, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationIn(List<Integer> values) {
            addCriterion("Radiation in", values, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationNotIn(List<Integer> values) {
            addCriterion("Radiation not in", values, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationBetween(Integer value1, Integer value2) {
            addCriterion("Radiation between", value1, value2, "radiation");
            return (Criteria) this;
        }

        public Criteria andRadiationNotBetween(Integer value1, Integer value2) {
            addCriterion("Radiation not between", value1, value2, "radiation");
            return (Criteria) this;
        }

        public Criteria andVlotIsNull() {
            addCriterion("Vlot is null");
            return (Criteria) this;
        }

        public Criteria andVlotIsNotNull() {
            addCriterion("Vlot is not null");
            return (Criteria) this;
        }

        public Criteria andVlotEqualTo(Float value) {
            addCriterion("Vlot =", value, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotNotEqualTo(Float value) {
            addCriterion("Vlot <>", value, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotGreaterThan(Float value) {
            addCriterion("Vlot >", value, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotGreaterThanOrEqualTo(Float value) {
            addCriterion("Vlot >=", value, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotLessThan(Float value) {
            addCriterion("Vlot <", value, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotLessThanOrEqualTo(Float value) {
            addCriterion("Vlot <=", value, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotIn(List<Float> values) {
            addCriterion("Vlot in", values, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotNotIn(List<Float> values) {
            addCriterion("Vlot not in", values, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotBetween(Float value1, Float value2) {
            addCriterion("Vlot between", value1, value2, "vlot");
            return (Criteria) this;
        }

        public Criteria andVlotNotBetween(Float value1, Float value2) {
            addCriterion("Vlot not between", value1, value2, "vlot");
            return (Criteria) this;
        }

        public Criteria andCurrent1IsNull() {
            addCriterion("Current1 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent1IsNotNull() {
            addCriterion("Current1 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent1EqualTo(Float value) {
            addCriterion("Current1 =", value, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1NotEqualTo(Float value) {
            addCriterion("Current1 <>", value, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1GreaterThan(Float value) {
            addCriterion("Current1 >", value, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1GreaterThanOrEqualTo(Float value) {
            addCriterion("Current1 >=", value, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1LessThan(Float value) {
            addCriterion("Current1 <", value, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1LessThanOrEqualTo(Float value) {
            addCriterion("Current1 <=", value, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1In(List<Float> values) {
            addCriterion("Current1 in", values, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1NotIn(List<Float> values) {
            addCriterion("Current1 not in", values, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1Between(Float value1, Float value2) {
            addCriterion("Current1 between", value1, value2, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent1NotBetween(Float value1, Float value2) {
            addCriterion("Current1 not between", value1, value2, "current1");
            return (Criteria) this;
        }

        public Criteria andCurrent2IsNull() {
            addCriterion("Current2 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent2IsNotNull() {
            addCriterion("Current2 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent2EqualTo(Float value) {
            addCriterion("Current2 =", value, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2NotEqualTo(Float value) {
            addCriterion("Current2 <>", value, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2GreaterThan(Float value) {
            addCriterion("Current2 >", value, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2GreaterThanOrEqualTo(Float value) {
            addCriterion("Current2 >=", value, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2LessThan(Float value) {
            addCriterion("Current2 <", value, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2LessThanOrEqualTo(Float value) {
            addCriterion("Current2 <=", value, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2In(List<Float> values) {
            addCriterion("Current2 in", values, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2NotIn(List<Float> values) {
            addCriterion("Current2 not in", values, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2Between(Float value1, Float value2) {
            addCriterion("Current2 between", value1, value2, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent2NotBetween(Float value1, Float value2) {
            addCriterion("Current2 not between", value1, value2, "current2");
            return (Criteria) this;
        }

        public Criteria andCurrent3IsNull() {
            addCriterion("Current3 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent3IsNotNull() {
            addCriterion("Current3 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent3EqualTo(Float value) {
            addCriterion("Current3 =", value, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3NotEqualTo(Float value) {
            addCriterion("Current3 <>", value, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3GreaterThan(Float value) {
            addCriterion("Current3 >", value, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3GreaterThanOrEqualTo(Float value) {
            addCriterion("Current3 >=", value, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3LessThan(Float value) {
            addCriterion("Current3 <", value, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3LessThanOrEqualTo(Float value) {
            addCriterion("Current3 <=", value, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3In(List<Float> values) {
            addCriterion("Current3 in", values, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3NotIn(List<Float> values) {
            addCriterion("Current3 not in", values, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3Between(Float value1, Float value2) {
            addCriterion("Current3 between", value1, value2, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent3NotBetween(Float value1, Float value2) {
            addCriterion("Current3 not between", value1, value2, "current3");
            return (Criteria) this;
        }

        public Criteria andCurrent4IsNull() {
            addCriterion("Current4 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent4IsNotNull() {
            addCriterion("Current4 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent4EqualTo(Float value) {
            addCriterion("Current4 =", value, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4NotEqualTo(Float value) {
            addCriterion("Current4 <>", value, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4GreaterThan(Float value) {
            addCriterion("Current4 >", value, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4GreaterThanOrEqualTo(Float value) {
            addCriterion("Current4 >=", value, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4LessThan(Float value) {
            addCriterion("Current4 <", value, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4LessThanOrEqualTo(Float value) {
            addCriterion("Current4 <=", value, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4In(List<Float> values) {
            addCriterion("Current4 in", values, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4NotIn(List<Float> values) {
            addCriterion("Current4 not in", values, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4Between(Float value1, Float value2) {
            addCriterion("Current4 between", value1, value2, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent4NotBetween(Float value1, Float value2) {
            addCriterion("Current4 not between", value1, value2, "current4");
            return (Criteria) this;
        }

        public Criteria andCurrent5IsNull() {
            addCriterion("Current5 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent5IsNotNull() {
            addCriterion("Current5 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent5EqualTo(Float value) {
            addCriterion("Current5 =", value, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5NotEqualTo(Float value) {
            addCriterion("Current5 <>", value, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5GreaterThan(Float value) {
            addCriterion("Current5 >", value, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5GreaterThanOrEqualTo(Float value) {
            addCriterion("Current5 >=", value, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5LessThan(Float value) {
            addCriterion("Current5 <", value, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5LessThanOrEqualTo(Float value) {
            addCriterion("Current5 <=", value, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5In(List<Float> values) {
            addCriterion("Current5 in", values, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5NotIn(List<Float> values) {
            addCriterion("Current5 not in", values, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5Between(Float value1, Float value2) {
            addCriterion("Current5 between", value1, value2, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent5NotBetween(Float value1, Float value2) {
            addCriterion("Current5 not between", value1, value2, "current5");
            return (Criteria) this;
        }

        public Criteria andCurrent6IsNull() {
            addCriterion("Current6 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent6IsNotNull() {
            addCriterion("Current6 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent6EqualTo(Float value) {
            addCriterion("Current6 =", value, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6NotEqualTo(Float value) {
            addCriterion("Current6 <>", value, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6GreaterThan(Float value) {
            addCriterion("Current6 >", value, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6GreaterThanOrEqualTo(Float value) {
            addCriterion("Current6 >=", value, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6LessThan(Float value) {
            addCriterion("Current6 <", value, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6LessThanOrEqualTo(Float value) {
            addCriterion("Current6 <=", value, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6In(List<Float> values) {
            addCriterion("Current6 in", values, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6NotIn(List<Float> values) {
            addCriterion("Current6 not in", values, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6Between(Float value1, Float value2) {
            addCriterion("Current6 between", value1, value2, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent6NotBetween(Float value1, Float value2) {
            addCriterion("Current6 not between", value1, value2, "current6");
            return (Criteria) this;
        }

        public Criteria andCurrent7IsNull() {
            addCriterion("Current7 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent7IsNotNull() {
            addCriterion("Current7 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent7EqualTo(Float value) {
            addCriterion("Current7 =", value, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7NotEqualTo(Float value) {
            addCriterion("Current7 <>", value, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7GreaterThan(Float value) {
            addCriterion("Current7 >", value, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7GreaterThanOrEqualTo(Float value) {
            addCriterion("Current7 >=", value, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7LessThan(Float value) {
            addCriterion("Current7 <", value, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7LessThanOrEqualTo(Float value) {
            addCriterion("Current7 <=", value, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7In(List<Float> values) {
            addCriterion("Current7 in", values, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7NotIn(List<Float> values) {
            addCriterion("Current7 not in", values, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7Between(Float value1, Float value2) {
            addCriterion("Current7 between", value1, value2, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent7NotBetween(Float value1, Float value2) {
            addCriterion("Current7 not between", value1, value2, "current7");
            return (Criteria) this;
        }

        public Criteria andCurrent8IsNull() {
            addCriterion("Current8 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent8IsNotNull() {
            addCriterion("Current8 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent8EqualTo(Float value) {
            addCriterion("Current8 =", value, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8NotEqualTo(Float value) {
            addCriterion("Current8 <>", value, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8GreaterThan(Float value) {
            addCriterion("Current8 >", value, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8GreaterThanOrEqualTo(Float value) {
            addCriterion("Current8 >=", value, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8LessThan(Float value) {
            addCriterion("Current8 <", value, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8LessThanOrEqualTo(Float value) {
            addCriterion("Current8 <=", value, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8In(List<Float> values) {
            addCriterion("Current8 in", values, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8NotIn(List<Float> values) {
            addCriterion("Current8 not in", values, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8Between(Float value1, Float value2) {
            addCriterion("Current8 between", value1, value2, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent8NotBetween(Float value1, Float value2) {
            addCriterion("Current8 not between", value1, value2, "current8");
            return (Criteria) this;
        }

        public Criteria andCurrent9IsNull() {
            addCriterion("Current9 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent9IsNotNull() {
            addCriterion("Current9 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent9EqualTo(Float value) {
            addCriterion("Current9 =", value, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9NotEqualTo(Float value) {
            addCriterion("Current9 <>", value, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9GreaterThan(Float value) {
            addCriterion("Current9 >", value, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9GreaterThanOrEqualTo(Float value) {
            addCriterion("Current9 >=", value, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9LessThan(Float value) {
            addCriterion("Current9 <", value, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9LessThanOrEqualTo(Float value) {
            addCriterion("Current9 <=", value, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9In(List<Float> values) {
            addCriterion("Current9 in", values, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9NotIn(List<Float> values) {
            addCriterion("Current9 not in", values, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9Between(Float value1, Float value2) {
            addCriterion("Current9 between", value1, value2, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent9NotBetween(Float value1, Float value2) {
            addCriterion("Current9 not between", value1, value2, "current9");
            return (Criteria) this;
        }

        public Criteria andCurrent10IsNull() {
            addCriterion("Current10 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent10IsNotNull() {
            addCriterion("Current10 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent10EqualTo(Float value) {
            addCriterion("Current10 =", value, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10NotEqualTo(Float value) {
            addCriterion("Current10 <>", value, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10GreaterThan(Float value) {
            addCriterion("Current10 >", value, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10GreaterThanOrEqualTo(Float value) {
            addCriterion("Current10 >=", value, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10LessThan(Float value) {
            addCriterion("Current10 <", value, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10LessThanOrEqualTo(Float value) {
            addCriterion("Current10 <=", value, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10In(List<Float> values) {
            addCriterion("Current10 in", values, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10NotIn(List<Float> values) {
            addCriterion("Current10 not in", values, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10Between(Float value1, Float value2) {
            addCriterion("Current10 between", value1, value2, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent10NotBetween(Float value1, Float value2) {
            addCriterion("Current10 not between", value1, value2, "current10");
            return (Criteria) this;
        }

        public Criteria andCurrent11IsNull() {
            addCriterion("Current11 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent11IsNotNull() {
            addCriterion("Current11 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent11EqualTo(Float value) {
            addCriterion("Current11 =", value, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11NotEqualTo(Float value) {
            addCriterion("Current11 <>", value, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11GreaterThan(Float value) {
            addCriterion("Current11 >", value, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11GreaterThanOrEqualTo(Float value) {
            addCriterion("Current11 >=", value, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11LessThan(Float value) {
            addCriterion("Current11 <", value, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11LessThanOrEqualTo(Float value) {
            addCriterion("Current11 <=", value, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11In(List<Float> values) {
            addCriterion("Current11 in", values, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11NotIn(List<Float> values) {
            addCriterion("Current11 not in", values, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11Between(Float value1, Float value2) {
            addCriterion("Current11 between", value1, value2, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent11NotBetween(Float value1, Float value2) {
            addCriterion("Current11 not between", value1, value2, "current11");
            return (Criteria) this;
        }

        public Criteria andCurrent12IsNull() {
            addCriterion("Current12 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent12IsNotNull() {
            addCriterion("Current12 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent12EqualTo(Float value) {
            addCriterion("Current12 =", value, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12NotEqualTo(Float value) {
            addCriterion("Current12 <>", value, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12GreaterThan(Float value) {
            addCriterion("Current12 >", value, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12GreaterThanOrEqualTo(Float value) {
            addCriterion("Current12 >=", value, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12LessThan(Float value) {
            addCriterion("Current12 <", value, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12LessThanOrEqualTo(Float value) {
            addCriterion("Current12 <=", value, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12In(List<Float> values) {
            addCriterion("Current12 in", values, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12NotIn(List<Float> values) {
            addCriterion("Current12 not in", values, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12Between(Float value1, Float value2) {
            addCriterion("Current12 between", value1, value2, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent12NotBetween(Float value1, Float value2) {
            addCriterion("Current12 not between", value1, value2, "current12");
            return (Criteria) this;
        }

        public Criteria andCurrent13IsNull() {
            addCriterion("Current13 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent13IsNotNull() {
            addCriterion("Current13 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent13EqualTo(Float value) {
            addCriterion("Current13 =", value, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13NotEqualTo(Float value) {
            addCriterion("Current13 <>", value, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13GreaterThan(Float value) {
            addCriterion("Current13 >", value, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13GreaterThanOrEqualTo(Float value) {
            addCriterion("Current13 >=", value, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13LessThan(Float value) {
            addCriterion("Current13 <", value, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13LessThanOrEqualTo(Float value) {
            addCriterion("Current13 <=", value, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13In(List<Float> values) {
            addCriterion("Current13 in", values, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13NotIn(List<Float> values) {
            addCriterion("Current13 not in", values, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13Between(Float value1, Float value2) {
            addCriterion("Current13 between", value1, value2, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent13NotBetween(Float value1, Float value2) {
            addCriterion("Current13 not between", value1, value2, "current13");
            return (Criteria) this;
        }

        public Criteria andCurrent14IsNull() {
            addCriterion("Current14 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent14IsNotNull() {
            addCriterion("Current14 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent14EqualTo(Float value) {
            addCriterion("Current14 =", value, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14NotEqualTo(Float value) {
            addCriterion("Current14 <>", value, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14GreaterThan(Float value) {
            addCriterion("Current14 >", value, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14GreaterThanOrEqualTo(Float value) {
            addCriterion("Current14 >=", value, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14LessThan(Float value) {
            addCriterion("Current14 <", value, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14LessThanOrEqualTo(Float value) {
            addCriterion("Current14 <=", value, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14In(List<Float> values) {
            addCriterion("Current14 in", values, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14NotIn(List<Float> values) {
            addCriterion("Current14 not in", values, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14Between(Float value1, Float value2) {
            addCriterion("Current14 between", value1, value2, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent14NotBetween(Float value1, Float value2) {
            addCriterion("Current14 not between", value1, value2, "current14");
            return (Criteria) this;
        }

        public Criteria andCurrent15IsNull() {
            addCriterion("Current15 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent15IsNotNull() {
            addCriterion("Current15 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent15EqualTo(Float value) {
            addCriterion("Current15 =", value, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15NotEqualTo(Float value) {
            addCriterion("Current15 <>", value, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15GreaterThan(Float value) {
            addCriterion("Current15 >", value, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15GreaterThanOrEqualTo(Float value) {
            addCriterion("Current15 >=", value, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15LessThan(Float value) {
            addCriterion("Current15 <", value, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15LessThanOrEqualTo(Float value) {
            addCriterion("Current15 <=", value, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15In(List<Float> values) {
            addCriterion("Current15 in", values, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15NotIn(List<Float> values) {
            addCriterion("Current15 not in", values, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15Between(Float value1, Float value2) {
            addCriterion("Current15 between", value1, value2, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent15NotBetween(Float value1, Float value2) {
            addCriterion("Current15 not between", value1, value2, "current15");
            return (Criteria) this;
        }

        public Criteria andCurrent16IsNull() {
            addCriterion("Current16 is null");
            return (Criteria) this;
        }

        public Criteria andCurrent16IsNotNull() {
            addCriterion("Current16 is not null");
            return (Criteria) this;
        }

        public Criteria andCurrent16EqualTo(Float value) {
            addCriterion("Current16 =", value, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16NotEqualTo(Float value) {
            addCriterion("Current16 <>", value, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16GreaterThan(Float value) {
            addCriterion("Current16 >", value, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16GreaterThanOrEqualTo(Float value) {
            addCriterion("Current16 >=", value, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16LessThan(Float value) {
            addCriterion("Current16 <", value, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16LessThanOrEqualTo(Float value) {
            addCriterion("Current16 <=", value, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16In(List<Float> values) {
            addCriterion("Current16 in", values, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16NotIn(List<Float> values) {
            addCriterion("Current16 not in", values, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16Between(Float value1, Float value2) {
            addCriterion("Current16 between", value1, value2, "current16");
            return (Criteria) this;
        }

        public Criteria andCurrent16NotBetween(Float value1, Float value2) {
            addCriterion("Current16 not between", value1, value2, "current16");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table environment
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 12 22:26:17 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}