package com.example.webdemo.dao.mapper;

import com.example.webdemo.dao.Environment;
import com.example.webdemo.dao.EnvironmentExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Mapper;

/**
 * MyBatis数据库连接层，具体的sql实现在resources/mapper/*.xml文件里
 */
@Mapper
public interface EnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    int countByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    int deleteByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    int insert(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    int insertSelective(Environment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    List<Environment> selectByExample(EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") Environment record, @Param("example") EnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table environment
     *
     * @mbggenerated Wed Aug 12 22:26:17 CST 2020
     */
    int updateByExample(@Param("record") Environment record, @Param("example") EnvironmentExample example);

    List<Environment> selectByTimeRange( String startDate, String endDate);

    List<Environment> selectOrderByDate();
}